### ISSUE TITLE
Use a more modern version of sc2reader

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ggpyjobs#1]
Currently we use an old and behind version of sc2reader: https://github.com/ggtracker/sc2reader/tree/upstream

Which is less efficient, and also not as easily compatible with the newer sc2reader.

**Comment by dmpaul26** [comment]
Since the version currently used is a bunch of commits ahead and behind the newer sc2reader, my thought was comparing the two branches and going through each commit from the newer sc2reader and make sure they are compatible, one by one?

**Comment by dsjoerg** [comment]
This would be difficult, more difficult than all the other things we've talked about doing.

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#26
